[Interface]
PrivateKey = {{ private_key }}
Address = {{ interface_address }}

[Peer]
PublicKey = {{ server_public_key }}
Endpoint = {{ endpoint }}
AllowedIPs = {{ allowed_ips }}
PersistentKeepalive = {{ persistent_keepalive }}
