[connect]
command:/usr/local/opnsense/scripts/OPNsense/OPNsenseHub/connect.py
type:script_output
message:connecting OPNsense Hub

[disconnect]
command:/usr/local/opnsense/scripts/OPNsense/OPNsenseHub/disconnect.py
type:script_output
message:disconnecting OPNsense Hub

[status]
command:/usr/local/opnsense/scripts/OPNsense/OPNsenseHub/status.py
type:script_output
message:checking OPNsense Hub status

[heartbeat]
command:/usr/local/opnsense/scripts/OPNsense/OPNsenseHub/heartbeat.py
type:script_output
message:sending OPNsense Hub heartbeat
