PLUGIN_NAME=          opnsensehub
PLUGIN_VERSION=       0.1
PLUGIN_COMMENT=       OPNsense Hub enrollment client
PLUGIN_MAINTAINER=    admin@example.com
PLUGIN_LICENSE=       BSD2CLAUSE
PLUGIN_DEPENDS=       wireguard-tools

.include "../../Mk/plugins.mk"
